title: Somi Jeong
logo: /assets/img/logo.png
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. Student at Yonsei University
  Seoul, South Korea
  <br><br>
  <a href="somijeong@yonsei.ac.kr">Email</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">LinkedIn</a> 
  <br><br>
theme: jekyll-theme-minimal
