title: Somi Jeong
logo: /assets/img/IMG_8357.jpg
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer Vision Engineer at NAVER LABS corp.
  Gyeonggi, South Korea
  <br><br>
  <a href="mailto:somiekd@gmail.com">Email</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/somi-jeong-1284728d8/">LinkedIn</a> 
  <br><br>
theme: jekyll-theme-minimal
