title: Jaehoon Cho
logo: /assets/img/jhcho.jpg
description: > # your text below (remove <br> elements if you don't need line breaks)
  **Hyundai Motor Company**<br>
  **Seoul, South Korea**
  <br><br>
  <a href="mailto:dnfleb@gmail.com">Email</a> 
  <br>
  <a href="https://www.linkedin.com/in/jhcho90/">LinkedIn</a> 
  <br>
  <a href="https://scholar.google.com/citations?user=5ixrVS8AAAAJ&hl=ko">GoogleScholar</a> 
  <br><br>
theme: jekyll-theme-minimal
