title: Somi Jeong
logo: /assets/img/logo.png
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. Student
  <br>
  Yonsei University, Seoul, Korea
  <br>
  <a href="https://www.linkedin.com/in/example/">My LinkedIn Profile</a> 
  <br>
theme: jekyll-theme-minimal
