title: Jaehoon Cho
logo: /assets/img/sihyun_jhc.jpg
description: > # your text below (remove <br> elements if you don't need line breaks)
  Korea Aerospace University<br>
  Goyang, South Korea
  <br><br>
  <a href="mailto:jh.cho@kau.ac.kr">Email</a> 
  <br>
  <a href="https://www.linkedin.com/in/jhcho90/">LinkedIn</a> 
  <br>
  <a href="https://scholar.google.com/citations?user=5ixrVS8AAAAJ&hl=ko">GoogleScholar</a> 
  <br><br>
theme: jekyll-theme-minimal
