title: Somi Jeong
logo: /assets/img/logo.png
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
